/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ano-ui/components/AButton/AButton.vue')['default']
    APage: typeof import('ano-ui/components/APage/APage.vue')['default']
    AToast: typeof import('ano-ui/components/AToast/AToast.vue')['default']
    DeviceList: typeof import('./components/UBasePage/DeviceList.vue')['default']
    UBasePage: typeof import('./components/UBasePage/UBasePage.vue')['default']
  }
}
